### ISSUE TITLE
Small edits to Introduction

### ISSUE THREAD

**Issue by sstmartin1** [LibraryCarpentry/lc-marcedit#10]
Here are two small edits to consider in the [Introduction](http://librarycarpentry.org/lc-marcedit/01-introduction/index.html)

1. **Downloading MarcEdit**: remove the word "Windows" which is listed twice.
Original text: MarcEdit was originally written for Windows but there are now versions available for Windows, Mac and Linux.
Suggested text: MarcEdit was originally written for Windows but there are now versions available for Mac and Linux.

2. **Exercise 1: Opening MARC records in the MarcEditor**: condense wording.
Original text: To edit a record, you need to open a file which contains one or more MARC records. This can be done (as you might expect) using the usual File menu, Open option, or by clicking the appropriate icon in the MarcEditor toolbar (second from the left).
Suggested text: To edit a record, you need to open a file which contains one or more MARC records. This can be done by clicking File->Open, or by clicking the yellow file icon in the MarcEditor toolbar (second from the left).

Thank you for considering!

**Comment by jenmawe** [comment]
Hello @sstmartinMCL,
Thank you for suggesting those edits. We will definitely take those into consideration. At the moment, we have just finished making our templates. Over the next several months we will be adding content and then review as we go along.
