### ISSUE TITLE
Need jump lists (anchors) for headings

### ISSUE THREAD

**Issue by annajiat** [LibraryCarpentry/lc-marcedit#21]
@zkamvar
We need to update style for this lesson so that jump lists (anchors for different sections) becomes automatically available for different levels of headings.

**Comment by ostephens** [comment]
@annajiat @zkamvar are there some directions on what we need to do to update the style appropriately? Happy to do the work if I know what needs to happen

**Comment by annajiat** [comment]
@ostephens 
Here it is
https://github.com/carpentries/maintainer-resources/blob/main/FLIGHT_RULES.md#update-styles

A detailed discussion is at
https://github.com/datacarpentry/python-ecology-lesson/issues/503#issuecomment-1021452938
