### ISSUE TITLE
Reorder Going Further section in Episode 1

### ISSUE THREAD

**Issue by sarahemlin** [LibraryCarpentry/lc-marcedit#5]
I'd like to suggest shifting the subsection "Going Further" in _episodes/01-introduction.md go at the end of the MarcEdit Interface section (which is currently just below Going Further).  I think the information about customizing your interface makes more sense to read after you're read the explanation of how the interface works.

**Comment by jenmawe** [comment]
@sarahemlin Thanks for the suggestion. Once we get back together, we'll certainly take it into account.
